//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBScoreboard
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BBScoreboardEntities : DbContext
    {
        public BBScoreboardEntities()
            : base("name=BBScoreboardEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BasketballPosition> BasketballPositions { get; set; }
        public virtual DbSet<UCGamePlayerStat> UCGamePlayerStats { get; set; }
        public virtual DbSet<UCSeason> UCSeasons { get; set; }
        public virtual DbSet<UCGameTeamStat> UCGameTeamStats { get; set; }
        public virtual DbSet<UCGameplayAction> UCGameplayActions { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<UCPlayer> UCPlayers { get; set; }
        public virtual DbSet<UCTeam> UCTeams { get; set; }
        public virtual DbSet<UCGame> UCGames { get; set; }
        public virtual DbSet<AppConfig> AppConfigs { get; set; }
    }
}
