//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBScoreboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class UCGameplayAction
    {
        public int Id { get; set; }
        public int GameId { get; set; }
        public int Quarter { get; set; }
        public int TeamId { get; set; }
        public int PlayerId { get; set; }
        public int ActionCode { get; set; }
        public int Arg { get; set; }
        public int RecPlayerId { get; set; }
        public System.DateTime ActionDate { get; set; }
        public System.DateTime GameTime { get; set; }
        public int TeamScore1 { get; set; }
        public int TeamScore2 { get; set; }
        public int Status { get; set; }
        public System.DateTime LastUpdate { get; set; }
    }
}
