//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBScoreboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class UCGamePlayerStat
    {
        public int Id { get; set; }
        public int PlayerId { get; set; }
        public int FGA { get; set; }
        public int FGM { get; set; }
        public int GameId { get; set; }
        public int FGA3 { get; set; }
        public int FGM3 { get; set; }
        public int FTA { get; set; }
        public int FTM { get; set; }
        public int REBOFF { get; set; }
        public int REBDEF { get; set; }
        public int ASSIST { get; set; }
        public int STEAL { get; set; }
        public int BLOCK { get; set; }
        public int TURNOVER { get; set; }
        public int FOULPER { get; set; }
        public int FOULTECH { get; set; }
        public bool InFloor { get; set; }
        public int TeamId { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public int Quarter { get; set; }
    }
}
