//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBScoreboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class UCGameTeamStat
    {
        public int Id { get; set; }
        public int TeamId { get; set; }
        public int GameId { get; set; }
        public int Q1 { get; set; }
        public int Q2 { get; set; }
        public int Q3 { get; set; }
        public int Q4 { get; set; }
        public System.DateTime LastUpdate { get; set; }
    }
}
